### ISSUE TITLE
Citation Style Examples for Quarto

### ISSUE THREAD

**Issue by rgaiacs** [mcanouil/awesome-quarto#122]
### Link to suggestion

https://quarto-forge.gitlab.io/csl-style-examples/

### Targeted section

Official documentation & quickstarts

### Describe your suggestion

This is shameless self promotion. :-D

The website include links to some citation styles render by quarto.

### Checklist

- [X] checked if your suggestion is not already listed in __Awesome Quarto__ list.
- [X] checked if it can fit in an existed section or [open a discussion](https://github.com/mcanouil/awesome-quarto/discussions/new?category=ideas) to suggest any new sections..
- [X] checked when it's a repository if it's maintained (archived repository will be rejected).

**Comment by mcanouil** [comment]
Thanks for the suggestion!

I wonder how useful it is, because for example <https://www.zotero.org/styles>  (can be found in <https://quarto.org/docs/authoring/footnotes-and-citations.html#citation-style>) highlights a lot of styles with an "hover" example of the citation and bibliography format.
Yours seems quite limited.
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/8896044/193658079-a11e9140-3372-45f1-ab46-0e00ec328009.png">

**Comment by rgaiacs** [comment]
Pandoc (and Quarto) uses Citation Style Language but Pandoc implemented some custom features (see https://discourse.citationstyles.org/t/pandocs-author-in-text-citation/1775). https://www.zotero.org/styles shows how Quarto will render the citations for `[@jane]` but not for `@jane` because `@jane` is a Pandoc custom feature.

My project's goal is to help users to preview how Quarto will render `@jane` as it can be very different.

**Comment by mcanouil** [comment]
I see, then may I suggest to let your project mature a bit.
Also, having to download the file to visualise the rendered style is not at all practical.

As is, I don't feel to add it.

**Comment by mcanouil** [comment]
I am going to close this in its current form, I don't think it follows Awesome guidelines, as it more something aside Quarto.
